INSERT INTO `notes` (`id`, `etudiant_id`, `matiere_id`, `professeur_id`, `note`) VALUES 
(NULL, 'et_1', 'math', 'prof_math', '12.5'), 
(NULL, 'et_1', 'pc', 'prof_pc', '18'),
(NULL, 'et_1', 'svt', 'prof_svt', '11'),
(NULL, 'et_1', 'philo', 'prof_philo', '13'),
(NULL, 'et_1', 'mlg', 'prof_mlg', '17'),
(NULL, 'et_1', 'frs', 'prof_frs', '12'),
(NULL, 'et_1', 'ang', 'prof_ang', '10'),

(NULL, 'et_2', 'math', 'prof_math', '12'), 
(NULL, 'et_2', 'pc', 'prof_pc', '17'),
(NULL, 'et_2', 'svt', 'prof_svt', '14'),
(NULL, 'et_2', 'philo', 'prof_philo', '12'),
(NULL, 'et_2', 'mlg', 'prof_mlg', '16'),
(NULL, 'et_2', 'frs', 'prof_frs', '14'),
(NULL, 'et_2', 'ang', 'prof_ang', '17'),

(NULL, 'et_3', 'math', 'prof_math', '18'), 
(NULL, 'et_3', 'pc', 'prof_pc', '19'),
(NULL, 'et_3', 'svt', 'prof_svt', '13'),
(NULL, 'et_3', 'philo', 'prof_philo', '15'),
(NULL, 'et_3', 'mlg', 'prof_mlg', '12'),
(NULL, 'et_3', 'frs', 'prof_frs', '10'),
(NULL, 'et_3', 'ang', 'prof_ang', '11'),

(NULL, 'et_4', 'math', 'prof_math', '10'), 
(NULL, 'et_4', 'pc', 'prof_pc', '9'),
(NULL, 'et_4', 'svt', 'prof_svt', '10.5'),
(NULL, 'et_4', 'philo', 'prof_philo', '12.5'),
(NULL, 'et_4', 'mlg', 'prof_mlg', '17'),
(NULL, 'et_4', 'frs', 'prof_frs', '16'),
(NULL, 'et_4', 'ang', 'prof_ang', '13'),

(NULL, 'et_5', 'math', 'prof_math', '13'),
(NULL, 'et_5', 'pc', 'prof_pc', '10'),
(NULL, 'et_5', 'svt', 'prof_svt', '3'),
(NULL, 'et_5', 'philo', 'prof_philo', '8'),
(NULL, 'et_5', 'mlg', 'prof_mlg', '18'),
(NULL, 'et_5', 'frs', 'prof_frs', '15.5'),
(NULL, 'et_5', 'ang', 'prof_ang', '11');